dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: change
language: node_js
node_js:
  - "9"
auth: &Auth |
  eval "$(npx travis-env)"
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - npm i -g npm@latest
  - npm ci
jobs:
  include:
  - stage: lint
    name: Lint
    script:
      - npm run lint
  - stage: build
    name: Build Docker Image
    script:
      - *Auth
      - npm run build:production
      - docker build . -t eventology/base-web-app:latest
      - docker push eventology/base-web-app:latest
stages:
- lint
- build
